import { useEffect, useState } from 'react';
import { CircleDollarSign, Plus, Search, WalletCards, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { produccionService } from '../../services/produccion.service';
import { api } from '../../services/api';

export default function CuentasCobrarPage(){
 const [data,setData]=useState<any>({cuentas:[],resumen:{}}); const [members,setMembers]=useState<any[]>([]); const [methods,setMethods]=useState<any[]>([]); const [filter,setFilter]=useState(''); const [create,setCreate]=useState(false); const [pay,setPay]=useState<any>(null);
 const [form,setForm]=useState<any>({miembroId:'',concepto:'Membresía',montoTotal:'',saldoInicial:'',fechaVencimiento:new Date().toISOString().slice(0,10),observaciones:''}); const [payment,setPayment]=useState<any>({metodoId:'',monto:'',numeroOperacion:'',observaciones:''});
 const load=async()=>{const [c,m,p]=await Promise.all([produccionService.listarCartera(),api.get('/miembros'),api.get('/pagos/metodos')]);setData(c);setMembers(m.data);setMethods(p.data.filter((x:any)=>x.activo));}; useEffect(()=>{load().catch(()=>toast.error('No se pudo cargar cartera'));},[]);
 const submit=async()=>{try{await produccionService.crearCuenta({...form,miembroId:Number(form.miembroId),montoTotal:Number(form.montoTotal),saldoInicial:form.saldoInicial===''?Number(form.montoTotal):Number(form.saldoInicial),fechaVencimiento:new Date(`${form.fechaVencimiento}T23:59:59`).toISOString()});toast.success('Cuenta creada');setCreate(false);load();}catch(e:any){toast.error(e.response?.data?.mensaje||'No se pudo crear');}};
 const submitPay=async()=>{try{await produccionService.registrarAbono(pay.id,{...payment,metodoId:Number(payment.metodoId),monto:Number(payment.monto)});toast.success('Abono registrado');setPay(null);setPayment({metodoId:'',monto:'',numeroOperacion:'',observaciones:''});load();}catch(e:any){toast.error(e.response?.data?.mensaje||'No se pudo cobrar');}};
 const rows=data.cuentas.filter((c:any)=>!filter||c.estado===filter);
 return <div className="p-4 md:p-6 max-w-[1600px] mx-auto space-y-4 text-gray-900"><div className="module-header bg-white p-4 rounded-xl border shadow-sm flex justify-between gap-4"><div className="flex gap-3"><div className="p-2.5 bg-yellow-50 text-[#e6b010] rounded-lg"><CircleDollarSign className="w-5 h-5"/></div><div><h1 className="font-bold">Cuentas por cobrar</h1><p className="text-[11px] text-gray-500">Deudas, vencimientos y abonos parciales de socios.</p></div></div><button onClick={()=>setCreate(true)} className="px-4 py-2 bg-gray-900 text-white rounded-lg text-xs flex items-center gap-2"><Plus className="w-4 h-4"/>Nueva cuenta</button></div>
 <div className="grid sm:grid-cols-3 gap-3"><Metric label="Cartera emitida" n={data.resumen.total}/><Metric label="Saldo pendiente" n={data.resumen.saldo}/><Metric label="Cartera vencida" n={data.resumen.vencido} red/></div>
 <div className="bg-white border rounded-xl shadow-sm"><div className="p-3 border-b flex gap-2"><Search className="w-4 h-4 text-gray-400"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="text-xs outline-none"><option value="">Todos los estados</option>{['PENDIENTE','PARCIAL','VENCIDA','PAGADA','ANULADA'].map(x=><option key={x}>{x}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-gray-50 text-[10px] uppercase text-gray-500"><tr><th className="p-3 text-left">Cuenta / socio</th><th className="p-3 text-left">Concepto</th><th className="p-3 text-right">Total</th><th className="p-3 text-right">Saldo</th><th className="p-3 text-left">Vence</th><th className="p-3">Estado</th><th></th></tr></thead><tbody className="divide-y">{rows.map((c:any)=><tr key={c.id} className="hover:bg-gray-50"><td className="p-3"><b>{c.codigo}</b><div>{c.miembro.nombres} {c.miembro.apellidos}</div></td><td className="p-3">{c.concepto}</td><td className="p-3 text-right">S/ {Number(c.montoTotal).toFixed(2)}</td><td className="p-3 text-right font-bold">S/ {Number(c.saldo).toFixed(2)}</td><td className="p-3">{new Date(c.fechaVencimiento).toLocaleDateString('es-PE')}</td><td className="p-3 text-center"><span className={`px-2 py-1 rounded text-[10px] font-bold ${c.estado==='PAGADA'?'bg-green-50 text-green-700':c.estado==='VENCIDA'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{c.estado}</span></td><td className="p-3 text-right">{!['PAGADA','ANULADA'].includes(c.estado)&&<button onClick={()=>{setPay(c);setPayment({...payment,monto:String(c.saldo)})}} className="px-3 py-1.5 bg-gray-900 text-white rounded-lg">Registrar abono</button>}</td></tr>)}</tbody></table></div></div>
 {create&&<Modal title="Nueva cuenta por cobrar" close={()=>setCreate(false)} action={submit}><div className="grid sm:grid-cols-2 gap-3"><Field label="Socio"><select value={form.miembroId} onChange={e=>setForm({...form,miembroId:e.target.value})} className="input"><option value="">Seleccionar...</option>{members.map(m=><option key={m.id} value={m.id}>{m.dni} · {m.nombres} {m.apellidos}</option>)}</select></Field><Field label="Concepto"><input className="input" value={form.concepto} onChange={e=>setForm({...form,concepto:e.target.value})}/></Field><Field label="Monto total"><input className="input" type="number" min="0.01" step="0.01" value={form.montoTotal} onChange={e=>setForm({...form,montoTotal:e.target.value})}/></Field><Field label="Saldo inicial"><input className="input" type="number" min="0" step="0.01" placeholder="Igual al total" value={form.saldoInicial} onChange={e=>setForm({...form,saldoInicial:e.target.value})}/></Field><Field label="Fecha de vencimiento"><input className="input" type="date" value={form.fechaVencimiento} onChange={e=>setForm({...form,fechaVencimiento:e.target.value})}/></Field></div></Modal>}
 {pay&&<Modal title={`Abono · ${pay.codigo}`} close={()=>setPay(null)} action={submitPay}><div className="grid sm:grid-cols-2 gap-3"><Field label="Método de pago"><select className="input" value={payment.metodoId} onChange={e=>setPayment({...payment,metodoId:e.target.value})}><option value="">Seleccionar...</option>{methods.map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select></Field><Field label={`Monto (saldo S/ ${Number(pay.saldo).toFixed(2)})`}><input className="input" type="number" min="0.01" max={pay.saldo} step="0.01" value={payment.monto} onChange={e=>setPayment({...payment,monto:e.target.value})}/></Field><Field label="Número de operación"><input className="input" value={payment.numeroOperacion} onChange={e=>setPayment({...payment,numeroOperacion:e.target.value})}/></Field></div></Modal>}
 </div>;
}
function Metric({label,n,red}:any){return <div className="bg-white border rounded-xl p-4 shadow-sm"><p className="text-[10px] uppercase font-bold text-gray-500">{label}</p><b className={`text-xl ${red?'text-red-600':''}`}>S/ {Number(n||0).toFixed(2)}</b></div>}
function Field({label,children}:any){return <label><span className="block text-[10px] uppercase font-bold text-gray-500 mb-1">{label}</span>{children}</label>}
function Modal({title,close,action,children}:any){return <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-xl"><div className="p-4 border-b flex justify-between"><b>{title}</b><button onClick={close}><X className="w-5 h-5"/></button></div><div className="p-5">{children}</div><div className="p-4 border-t flex justify-end gap-2"><button onClick={close} className="px-4 py-2 border rounded-lg text-xs">Cancelar</button><button onClick={action} className="px-4 py-2 bg-gray-900 text-white rounded-lg text-xs flex gap-2"><WalletCards className="w-4 h-4"/>Guardar</button></div></div></div>}
