import { useEffect, useState } from 'react';
import { BadgeCheck, FileCheck2, Search, Save, X, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';
import { produccionService } from '../../services/produccion.service';

const empty = { tipo: 'BOLETA', estado: 'PENDIENTE', proveedor: 'SEE_SOL', clienteTipoDoc: 'DNI', clienteNumeroDoc: '', clienteRazonSocial: '', clienteDireccion: '', serie: '', correlativo: '', fechaEmision: '', enlaceConsulta: '', observaciones: '' };
export default function ControlFiscalPage() {
  const [ventas, setVentas] = useState<any[]>([]); const [search, setSearch] = useState(''); const [edit, setEdit] = useState<any>(null); const [form, setForm] = useState<any>(empty); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setVentas(await produccionService.listarFiscal(search)); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const open = (v: any) => { const f = v.comprobanteFiscal || {}; setEdit(v); setForm({ ...empty, ...f, fechaEmision: f.fechaEmision ? new Date(f.fechaEmision).toISOString().slice(0, 16) : '' }); };
  const save = async () => { try { await produccionService.actualizarFiscal(edit.id, { ...form, fechaEmision: form.fechaEmision ? new Date(form.fechaEmision).toISOString() : null, enlaceConsulta: form.enlaceConsulta || null }); toast.success('Control fiscal actualizado'); setEdit(null); load(); } catch (e: any) { toast.error(e.response?.data?.mensaje || 'No se pudo guardar'); } };
  const pendientes = ventas.filter(v => ['PENDIENTE'].includes(v.comprobanteFiscal?.estado)).length; const emitidos = ventas.filter(v => ['EMITIDO','ACEPTADO'].includes(v.comprobanteFiscal?.estado)).length;
  return <div className="p-4 md:p-6 max-w-[1600px] mx-auto space-y-4 text-gray-900">
    <div className="module-header bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex flex-col sm:flex-row justify-between gap-4"><div className="flex gap-3"><div className="p-2.5 bg-yellow-50 border border-yellow-100 rounded-lg text-[#e6b010]"><FileCheck2 className="w-5 h-5"/></div><div><h1 className="text-base font-bold">Control de comprobantes SUNAT</h1><p className="text-[11px] text-gray-500">Registra el comprobante emitido externamente en SEE-SOL, PSE u OSE.</p></div></div><div className="flex"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Código o cliente" className="border rounded-l-lg px-3 text-xs outline-none"/><button onClick={load} className="bg-gray-900 text-white px-3 rounded-r-lg"><Search className="w-4 h-4"/></button></div></div>
    <div className="grid sm:grid-cols-3 gap-3"><Card label="Ventas revisadas" value={ventas.length}/><Card label="Pendientes de emisión" value={pendientes} warn/><Card label="Emitidos / aceptados" value={emitidos} ok/></div>
    <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 flex gap-2 text-xs text-amber-900"><AlertTriangle className="w-4 h-4 shrink-0"/><span>TemploGym no envía documentos a SUNAT todavía. Emite en el portal o proveedor autorizado y registra aquí la referencia. Los tickets internos no tienen valor tributario.</span></div>
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-x-auto"><table className="w-full text-xs"><thead className="bg-gray-50 text-[10px] uppercase text-gray-500"><tr><th className="text-left p-3">Venta</th><th className="text-left p-3">Cliente</th><th className="text-left p-3">Tipo</th><th className="text-left p-3">Comprobante SUNAT</th><th className="text-left p-3">Estado</th><th className="p-3"></th></tr></thead><tbody className="divide-y">{ventas.map(v=><tr key={v.id} className="hover:bg-gray-50"><td className="p-3"><b>{v.codigo}</b><div className="text-gray-400">{new Date(v.createdAt).toLocaleString('es-PE')}</div></td><td className="p-3">{v.cliente}</td><td className="p-3">{v.comprobanteFiscal?.tipo || 'TICKET_INTERNO'}</td><td className="p-3 font-mono">{v.comprobanteFiscal?.serie ? `${v.comprobanteFiscal.serie}-${v.comprobanteFiscal.correlativo}` : 'Sin emitir'}</td><td className="p-3"><Status value={v.comprobanteFiscal?.estado || 'NO_APLICA'}/></td><td className="p-3 text-right"><button onClick={()=>open(v)} className="px-3 py-1.5 bg-gray-900 text-white rounded-lg">Gestionar</button></td></tr>)}</tbody></table>{!loading&&!ventas.length&&<p className="p-10 text-center text-gray-400 text-xs">No hay ventas.</p>}</div>
    {edit&&<div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"><div className="p-4 border-b flex justify-between"><div><b>Control fiscal · {edit.codigo}</b><p className="text-xs text-gray-500">Total S/ {Number(edit.total).toFixed(2)}</p></div><button onClick={()=>setEdit(null)}><X className="w-5 h-5"/></button></div><div className="p-5 grid sm:grid-cols-2 gap-3">{[['tipo','Tipo','select',['TICKET_INTERNO','BOLETA','FACTURA','NOTA_CREDITO','NOTA_DEBITO']],['estado','Estado','select',['NO_APLICA','PENDIENTE','EMITIDO','ACEPTADO','RECHAZADO','ANULADO']],['proveedor','Canal','select',['NINGUNO','SEE_SOL','PSE','OSE']],['clienteTipoDoc','Tipo documento','select',['DNI','RUC','CE','OTRO']],['clienteNumeroDoc','N.º documento'],['clienteRazonSocial','Razón social / nombre'],['clienteDireccion','Dirección fiscal'],['serie','Serie'],['correlativo','Correlativo'],['fechaEmision','Fecha de emisión','datetime-local'],['enlaceConsulta','Enlace de consulta']].map((x:any)=><label key={x[0]} className={x[0]==='enlaceConsulta'?'sm:col-span-2':''}><span className="block text-[10px] uppercase font-bold text-gray-500 mb-1">{x[1]}</span>{x[2]==='select'?<select value={form[x[0]]||''} onChange={e=>setForm({...form,[x[0]]:e.target.value})} className="w-full border rounded-lg p-2 text-xs">{x[3].map((o:string)=><option key={o}>{o}</option>)}</select>:<input type={x[2]||'text'} value={form[x[0]]||''} onChange={e=>setForm({...form,[x[0]]:e.target.value})} className="w-full border rounded-lg p-2 text-xs"/>}</label>)}</div><div className="p-4 border-t flex justify-end gap-2"><button onClick={()=>setEdit(null)} className="px-4 py-2 text-xs border rounded-lg">Cancelar</button><button onClick={save} className="px-4 py-2 text-xs bg-[#141414] text-white rounded-lg flex gap-2"><Save className="w-4 h-4"/>Guardar</button></div></div></div>}
  </div>;
}
function Card({label,value,warn,ok}:any){return <div className="bg-white border rounded-xl p-4 shadow-sm"><p className="text-[10px] uppercase font-bold text-gray-500">{label}</p><div className="flex justify-between mt-1"><b className="text-xl">{value}</b>{ok?<BadgeCheck className="text-green-500"/>:warn?<AlertTriangle className="text-amber-500"/>:null}</div></div>}
function Status({value}:{value:string}){const good=['EMITIDO','ACEPTADO'].includes(value);return <span className={`px-2 py-1 rounded-md text-[10px] font-bold ${good?'bg-green-50 text-green-700':value==='RECHAZADO'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}>{value}</span>}
