import { FormEvent, useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { Banknote, Calculator, LockKeyhole, RefreshCw } from 'lucide-react';
import { operacionesService } from '../../services/operaciones.service';

const denominaciones = [
  { valor: 200, tipo: 'BILLETE' }, { valor: 100, tipo: 'BILLETE' }, { valor: 50, tipo: 'BILLETE' }, { valor: 20, tipo: 'BILLETE' }, { valor: 10, tipo: 'BILLETE' },
  { valor: 5, tipo: 'MONEDA' }, { valor: 2, tipo: 'MONEDA' }, { valor: 1, tipo: 'MONEDA' }, { valor: .5, tipo: 'MONEDA' }, { valor: .2, tipo: 'MONEDA' }, { valor: .1, tipo: 'MONEDA' },
] as const;
const dinero = (n: number) => `S/ ${Number(n || 0).toFixed(2)}`;

export default function CajaPage() {
  const [caja, setCaja] = useState<any>(null); const [montoInicial, setMontoInicial] = useState('');
  const [cantidades, setCantidades] = useState<Record<string, number>>({}); const [contados, setContados] = useState<Record<string, number>>({});
  const [observaciones, setObservaciones] = useState(''); const [procesando, setProcesando] = useState(false);
  const [errorConexion, setErrorConexion] = useState('');
  const mensajeError = (error: any) => error?.response?.data?.mensaje || error?.message || 'No se pudo conectar con el servidor.';
  const cargar = async () => { try { setErrorConexion(''); setCaja(await operacionesService.cajaActual()); } catch (error: any) { setErrorConexion(mensajeError(error)); } }; useEffect(() => { void cargar(); }, []);
  const efectivoContado = useMemo(() => denominaciones.reduce((s, d) => s + d.valor * (cantidades[String(d.valor)] || 0), 0), [cantidades]);
  const metodos = useMemo(() => caja?.resumenMetodos || [], [caja]);
  const totalEsperado = caja?.totalEsperado || 0;
  const totalContado = efectivoContado + metodos.filter((m: any) => !/efectivo/i.test(m.metodoNombre)).reduce((s: number, m: any) => s + Number(contados[String(m.metodoId)] ?? m.esperado), 0);
  const abrir = async (e: FormEvent) => { e.preventDefault(); setProcesando(true); try { setErrorConexion(''); await operacionesService.abrirCaja(Number(montoInicial)); toast.success('Caja abierta'); setMontoInicial(''); await cargar(); } catch (error: any) { const mensaje = mensajeError(error); setErrorConexion(mensaje); toast.error(mensaje); } finally { setProcesando(false); } };
  const cerrar = async () => { setProcesando(true); try { await operacionesService.cerrarCaja({ conteo: denominaciones.map(d => ({ denominacion: d.valor, cantidad: cantidades[String(d.valor)] || 0, tipo: d.tipo })), conciliaciones: metodos.map((m: any) => ({ metodoId: m.metodoId, metodoNombre: m.metodoNombre, contado: /efectivo/i.test(m.metodoNombre) ? efectivoContado : Number(contados[String(m.metodoId)] ?? m.esperado) })), observaciones }); toast.success('Cuadre guardado y caja cerrada'); setCantidades({}); setContados({}); await cargar(); } catch (error: any) { toast.error(mensajeError(error)); } finally { setProcesando(false); } };

  if (!caja) return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Caja y arqueo</h1><p className="text-sm text-gray-500">Abre un turno para registrar y conciliar las operaciones.</p></div>{errorConexion&&<div role="alert" className="max-w-lg rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700"><b>No se pudo abrir la caja.</b><div>{errorConexion}</div></div>}<form onSubmit={abrir} className="max-w-lg rounded-xl border bg-white p-6 shadow-sm"><Banknote className="mb-4 text-emerald-600"/><h2 className="font-semibold">Fondo inicial en efectivo</h2><input required min="0" step="0.01" type="number" value={montoInicial} onChange={e=>setMontoInicial(e.target.value)} className="mt-4 w-full rounded-lg border p-3" placeholder="0.00"/><button type="submit" disabled={procesando} className="mt-4 w-full rounded-lg bg-gray-900 p-3 font-semibold text-white disabled:cursor-wait disabled:opacity-60">{procesando?'Abriendo caja...':'Abrir caja'}</button></form></div>;

  return <div className="space-y-6 pb-12"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Hoja de cuadre de caja</h1><p className="text-sm text-gray-500">Turno abierto {new Date(caja.abiertaAt).toLocaleString()} · los importes esperados provienen de las operaciones reales.</p></div><button onClick={cargar} className="rounded-lg border bg-white p-2"><RefreshCw size={18}/></button></div>
    <div className="grid gap-6 xl:grid-cols-2"><section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="border-b bg-gray-50 px-5 py-4"><h2 className="font-semibold">1. Conteo físico de efectivo</h2><p className="text-xs text-gray-500">Billetes y monedas peruanas</p></div><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-gray-500"><th className="p-3">Tipo</th><th>Denominación</th><th className="w-28">Cantidad</th><th className="pr-4 text-right">Subtotal</th></tr></thead><tbody>{denominaciones.map(d=><tr key={`${d.tipo}-${d.valor}`} className="border-b last:border-0"><td className="p-3 text-xs text-gray-500">{d.tipo === 'BILLETE' ? 'Billete' : 'Moneda'}</td><td>{dinero(d.valor)}</td><td><input min="0" type="number" value={cantidades[String(d.valor)] || ''} onChange={e=>setCantidades({...cantidades,[String(d.valor)]:Math.max(0,Number(e.target.value))})} className="w-24 rounded border px-2 py-1.5 text-right"/></td><td className="pr-4 text-right font-medium">{dinero(d.valor*(cantidades[String(d.valor)]||0))}</td></tr>)}</tbody><tfoot><tr className="bg-emerald-50 text-emerald-800"><td colSpan={3} className="p-4 font-bold">TOTAL EFECTIVO CONTADO</td><td className="pr-4 text-right text-lg font-bold">{dinero(efectivoContado)}</td></tr></tfoot></table></section>
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="border-b bg-gray-50 px-5 py-4"><h2 className="font-semibold">2. Conciliación por método</h2><p className="text-xs text-gray-500">Efectivo, billeteras digitales y tarjetas se muestran por separado</p></div><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-gray-500"><th className="p-3">Método</th><th className="text-right">Sistema</th><th className="text-right">Contado / reporte</th><th className="pr-4 text-right">Diferencia</th></tr></thead><tbody>{metodos.map((m:any)=>{const esEfectivo=/efectivo/i.test(m.metodoNombre);const esperado=esEfectivo?caja.efectivoEsperado:m.esperado;const contado=esEfectivo?efectivoContado:Number(contados[String(m.metodoId)]??m.esperado);return <tr key={m.metodoId} className="border-b"><td className="p-3 font-medium">{m.metodoNombre}</td><td className="text-right">{dinero(esperado)}</td><td className="text-right">{esEfectivo?<span className="text-xs text-gray-500">Desde conteo</span>:<input step="0.01" min="0" type="number" value={contados[String(m.metodoId)]??m.esperado} onChange={e=>setContados({...contados,[String(m.metodoId)]:Number(e.target.value)})} className="w-28 rounded border px-2 py-1.5 text-right"/>}</td><td className={`pr-4 text-right font-semibold ${Math.abs(contado-esperado)<.01?'text-emerald-600':'text-red-600'}`}>{dinero(contado-esperado)}</td></tr>})}</tbody></table>{!metodos.length&&<p className="p-6 text-center text-sm text-gray-500">Aún no hay cobros en este turno.</p>}<div className="grid grid-cols-3 border-t bg-gray-50 p-4 text-center"><div><small className="text-gray-500">Esperado</small><b className="block">{dinero(totalEsperado)}</b></div><div><small className="text-gray-500">Contado</small><b className="block">{dinero(totalContado)}</b></div><div><small className="text-gray-500">Diferencia</small><b className={`block ${Math.abs(totalContado-totalEsperado)<.01?'text-emerald-600':'text-red-600'}`}>{dinero(totalContado-totalEsperado)}</b></div></div></section></div>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Calculator size={18}/><h2 className="font-semibold">3. Observación y cierre</h2></div><textarea value={observaciones} onChange={e=>setObservaciones(e.target.value)} className="mt-4 w-full rounded-lg border p-3 text-sm" rows={3} placeholder="Explica diferencias, retiros o incidencias del turno..."/><button disabled={procesando||!metodos.length} onClick={cerrar} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-red-600 p-3 font-semibold text-white disabled:opacity-50"><LockKeyhole size={18}/>Guardar arqueo y cerrar caja</button></section>
  </div>;
}
