import { useEffect, useState } from 'react';
import { Eye, History, Printer, RefreshCw, X } from 'lucide-react';
import { operacionesService } from '../../services/operaciones.service';
const dinero = (value: unknown) => `S/ ${Number(value || 0).toFixed(2)}`;

export default function HistorialCajaPage() {
  const [cajas, setCajas] = useState<any[]>([]); const [seleccionada, setSeleccionada] = useState<any>(null); const [cargando, setCargando] = useState(true);
  const cargar = async () => { setCargando(true); try { setCajas(await operacionesService.historialCajas()); } finally { setCargando(false); } };
  useEffect(() => { void cargar(); }, []);
  return <div className="p-4 md:p-6 max-w-[1600px] mx-auto space-y-4 text-gray-900"><style>{`@media print{body *{visibility:hidden}.arqueo-print,.arqueo-print *{visibility:visible}.arqueo-print{position:absolute;inset:0;width:100%;background:white;padding:24px}.no-print{display:none!important}}`}</style>
    <div className="no-print module-header bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex items-center justify-between"><div className="flex items-center gap-3"><div className="p-2.5 bg-yellow-50 rounded-lg border border-yellow-100 text-[#e6b010]"><History className="w-5 h-5"/></div><div><h1 className="text-base font-bold tracking-wide">Historial de Cuadres</h1><p className="text-[11px] text-gray-500 mt-0.5">Consulta, audita e imprime cada cierre de caja.</p></div></div><button onClick={cargar} className="rounded-lg border border-gray-200 bg-gray-50 p-2 text-gray-500"><RefreshCw className={`w-4 h-4 ${cargando?'animate-spin':''}`}/></button></div>
    <div className="no-print overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th className="p-4">Turno</th><th>Responsable</th><th>Estado</th><th className="text-right">Esperado</th><th className="text-right">Contado</th><th className="text-right">Diferencia</th><th className="p-4 text-right">Acciones</th></tr></thead><tbody>{cajas.map(c=><tr key={c.id} className="border-t"><td className="p-4"><b>CAJA-{String(c.id).padStart(6,'0')}</b><div className="text-xs text-gray-400">{new Date(c.abiertaAt).toLocaleString()} — {c.cerradaAt?new Date(c.cerradaAt).toLocaleString():'Abierta'}</div></td><td>{c.usuario.nombres} {c.usuario.apellidos}</td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${c.estado==='CERRADA'?'bg-gray-100':'bg-emerald-50 text-emerald-700'}`}>{c.estado}</span></td><td className="text-right">{dinero(c.montoEsperado)}</td><td className="text-right">{dinero(c.montoContado)}</td><td className={`text-right font-semibold ${Math.abs(Number(c.diferencia))<.01?'text-emerald-600':'text-red-600'}`}>{dinero(c.diferencia)}</td><td className="p-4 text-right"><button onClick={()=>setSeleccionada(c)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2"><Eye size={14}/>Ver</button></td></tr>)}</tbody></table>{!cargando&&!cajas.length&&<p className="p-10 text-center text-gray-500">Todavía no existen cuadres cerrados.</p>}</div>
    {seleccionada&&<div className="fixed inset-0 z-[70] overflow-y-auto bg-black/50 p-4"><article className="arqueo-print mx-auto my-6 max-w-4xl rounded-xl bg-white p-8 shadow-xl"><div className="no-print mb-6 flex justify-end gap-2"><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-lg bg-gray-900 px-4 py-2 text-white"><Printer size={16}/>Imprimir</button><button onClick={()=>setSeleccionada(null)} className="rounded-lg border p-2"><X size={18}/></button></div><header className="border-b pb-5"><h1 className="text-2xl font-bold">CUADRE DE CAJA</h1><div className="mt-2 grid grid-cols-2 gap-2 text-sm"><span><b>Número:</b> CAJA-{String(seleccionada.id).padStart(6,'0')}</span><span><b>Responsable:</b> {seleccionada.usuario.nombres} {seleccionada.usuario.apellidos}</span><span><b>Apertura:</b> {new Date(seleccionada.abiertaAt).toLocaleString()}</span><span><b>Cierre:</b> {seleccionada.cerradaAt?new Date(seleccionada.cerradaAt).toLocaleString():'—'}</span></div></header>
      <h2 className="mt-6 font-bold">Conteo de efectivo</h2><table className="mt-2 w-full text-sm"><thead className="bg-gray-100"><tr><th className="p-2 text-left">Tipo</th><th>Denominación</th><th>Cantidad</th><th className="text-right">Subtotal</th></tr></thead><tbody>{seleccionada.conteos.map((d:any)=><tr key={d.id} className="border-b"><td className="p-2">{d.tipo}</td><td className="text-center">{dinero(d.denominacion)}</td><td className="text-center">{d.cantidad}</td><td className="text-right">{dinero(d.subtotal)}</td></tr>)}</tbody></table>
      <h2 className="mt-6 font-bold">Conciliación de métodos de pago</h2><table className="mt-2 w-full text-sm"><thead className="bg-gray-100"><tr><th className="p-2 text-left">Método</th><th className="text-right">Esperado</th><th className="text-right">Contado</th><th className="text-right">Diferencia</th></tr></thead><tbody>{seleccionada.conciliaciones.map((m:any)=><tr key={m.id} className="border-b"><td className="p-2">{m.metodoNombre}</td><td className="text-right">{dinero(m.esperado)}</td><td className="text-right">{dinero(m.contado)}</td><td className="text-right">{dinero(m.diferencia)}</td></tr>)}</tbody><tfoot className="font-bold"><tr><td className="p-3">TOTALES</td><td className="text-right">{dinero(seleccionada.montoEsperado)}</td><td className="text-right">{dinero(seleccionada.montoContado)}</td><td className="text-right">{dinero(seleccionada.diferencia)}</td></tr></tfoot></table>
      {seleccionada.observaciones&&<div className="mt-6 rounded border p-3 text-sm"><b>Observaciones:</b> {seleccionada.observaciones}</div>}<div className="mt-16 grid grid-cols-2 gap-16 text-center text-sm"><div className="border-t pt-2">Responsable de caja</div><div className="border-t pt-2">Supervisor</div></div></article></div>}
  </div>;
}
