INSERT INTO "MetodoPago" ("nombre", "descripcion", "activo", "createdAt") VALUES
('Efectivo', 'Billetes y monedas en soles', true, CURRENT_TIMESTAMP),
('Yape', 'Billetera digital interoperable', true, CURRENT_TIMESTAMP),
('Plin', 'Billetera digital interoperable', true, CURRENT_TIMESTAMP),
('Bim', 'Billetera móvil', true, CURRENT_TIMESTAMP),
('QR interoperable', 'Pago mediante código QR interoperable', true, CURRENT_TIMESTAMP),
('Visa débito', 'Tarjeta de débito Visa', true, CURRENT_TIMESTAMP),
('Visa crédito', 'Tarjeta de crédito Visa', true, CURRENT_TIMESTAMP),
('Mastercard débito', 'Tarjeta de débito Mastercard', true, CURRENT_TIMESTAMP),
('Mastercard crédito', 'Tarjeta de crédito Mastercard', true, CURRENT_TIMESTAMP),
('American Express', 'Tarjeta American Express', true, CURRENT_TIMESTAMP),
('Diners Club', 'Tarjeta Diners Club', true, CURRENT_TIMESTAMP),
('UnionPay', 'Tarjeta UnionPay', true, CURRENT_TIMESTAMP),
('Transferencia BCP', 'Transferencia a cuenta BCP', true, CURRENT_TIMESTAMP),
('Transferencia Interbank', 'Transferencia a cuenta Interbank', true, CURRENT_TIMESTAMP),
('Transferencia BBVA', 'Transferencia a cuenta BBVA', true, CURRENT_TIMESTAMP),
('Transferencia Scotiabank', 'Transferencia a cuenta Scotiabank', true, CURRENT_TIMESTAMP),
('Transferencia BanBif', 'Transferencia a cuenta BanBif', true, CURRENT_TIMESTAMP),
('Transferencia Banco de la Nación', 'Transferencia a cuenta del Banco de la Nación', true, CURRENT_TIMESTAMP),
('Transferencia bancaria - Otros', 'Transferencia desde otra entidad financiera', true, CURRENT_TIMESTAMP),
('Depósito bancario', 'Depósito en ventanilla o agente', true, CURRENT_TIMESTAMP),
('PagoEfectivo', 'Código CIP de PagoEfectivo', true, CURRENT_TIMESTAMP),
('Mercado Pago', 'Billetera o enlace de Mercado Pago', true, CURRENT_TIMESTAMP),
('PayPal', 'Pago procesado por PayPal', true, CURRENT_TIMESTAMP),
('Cheque', 'Cheque bancario sujeto a confirmación', true, CURRENT_TIMESTAMP),
('Crédito interno', 'Saldo por cobrar autorizado', true, CURRENT_TIMESTAMP),
('Cortesía', 'Operación sin cobro autorizada', true, CURRENT_TIMESTAMP)
ON CONFLICT ("nombre") DO UPDATE SET
  "descripcion" = EXCLUDED."descripcion",
  "activo" = true;
